name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH }}

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 222 $SERVER_IP >> ~/.ssh/known_hosts
      env:
        SERVER_IP: ${{ secrets.HOST }}

    - name: Copy files to server
      run: |
        rsync -avz --exclude .git --exclude node_modules -e "ssh -p 222" ./ $SERVER_USER@$SERVER_IP:/opt/test
      env:
        SERVER_IP: ${{ secrets.HOST }}
        SERVER_USER: ${{ secrets.USER }}
